Introduction to NumPy
===

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [5]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print('Vector a:\n', a)
print('variable type', type(a)) # Prints "<class 'numpy.ndarray'>"
print('shape:', a.shape)        # Prints "(3,)"
print(a[0], a[1], a[2])         # Prints "1 2 3"
a[0] = 5                        # Change an element of the array

b = np.array([[1, 2, 3], [4, 5, 6]])    # Create a rank 2 array
print('Matrix b:\n', b)
print('shape:', b.shape)                # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

Vector a:
 [1 2 3]
variable type <class 'numpy.ndarray'>
shape: (3,)
1 2 3
Matrix b:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
1 2 4


If you want to change the shape of the ndarray

In [10]:
print('Matrix b:\n', b)
print('shape:', b.shape)
c = b.reshape((3, 2))
print('Matrix c:\n', c)

Matrix b:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Matrix b:
 [[1 2]
 [3 4]
 [5 6]]


Numpy also provides many functions to create arrays:

In [33]:
a = np.zeros((2, 2))   # Create an array of all zeros
print('a =', a)        # Prints "[[ 0.  0.]
                       #          [ 0.  0.]]"

b = np.ones((1, 2))    # Create an array of all ones
print('b =', b)        # Prints "[[ 1.  1.]]"

c = np.full((2, 2), 7)  # Create a constant array
print('c =', c)         # Prints "[[ 7.  7.]
                        #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print('d =', d)       # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2, 2))  # Create an array filled with random values
print('e =', e)               # Might print "[[ 0.91940167  0.08143941]
                              #               [ 0.68744134  0.87236687]]"
    
f = np.arange(6)            # Creates a range from 0 to 5 (a range with 6 elemets)
print('f =', f)

g = f.reshape((3, 2))       # Reshaping the array into a matrix of size (2,3)
print('g =', g)

a = [[0. 0.]
 [0. 0.]]
b = [[1. 1.]]
c = [[7 7]
 [7 7]]
d = [[1. 0.]
 [0. 1.]]
e = [[0.51055742 0.33174052]
 [0.64513607 0.25657699]]
f = [0 1 2 3 4 5]
g = [[0 1]
 [2 3]
 [4 5]]


*Note*: Regarding the shape of 1D ndarray it's shape is written as (n, ). It is fine to work with this array normally however for application that require clear distinction of the shape it is critical to watch out from this kind of arrays.Best example is matrix operation

In [36]:
x = np.arange(3)
# Notice the shape of x, now x can't be called as a row vector or column vector
x.shape
y = x.reshape((3, 1))
z = x.reshape((1, 3))
print('x:', x)
print('y:', y)
print('z:', z)
# This is very important when using linear algebra operations

x: [0 1 2]
y: [[0]
 [1]
 [2]]
z: [[0 1 2]]


## Array Indexing

In [37]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


## Array Data Types

In [38]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


## Operations

In [42]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
y = np.array([[5, 6, 7], [8, 9, 10]], dtype=np.float64)
# Elementwise sum; both produce the array
print('x + y =', x + y)
print('x + y =', np.add(x, y))

# Elementwise difference; both produce the array
print('x - y =', x - y)
print('x - y =', np.subtract(x, y))

# Elementwise product; both produce the array
print('x * y =', x * y)
print('x * y =', np.multiply(x, y))

# Elementwise division; both produce the array
print('x / y =', x / y)
print('x / y =', np.divide(x, y))

# Elementwise square root; produces the array
print('square root x =', np.sqrt(x))

# Return the array index of the maximum value
print('index of max elemet in x= ', np.argmax(x))

# Return the array indices of the maximum values per row
print('index of max elemet in axis 1 of x= ', np.argmax(x, axis=1))

# Return the array indices of the maximum values per column
print('index of max elemet in axis 0 of x= ', np.argmax(x, axis=0))

x + y = [[ 6.  8. 10.]
 [12. 14. 16.]]
x + y = [[ 6.  8. 10.]
 [12. 14. 16.]]
x - y = [[-4. -4. -4.]
 [-4. -4. -4.]]
x - y = [[-4. -4. -4.]
 [-4. -4. -4.]]
x * y = [[ 5. 12. 21.]
 [32. 45. 60.]]
x * y = [[ 5. 12. 21.]
 [32. 45. 60.]]
x / y = [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]
x / y = [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]
square root x = [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
index of max elemet in x=  5
index of max elemet in axis 1 of x=  [2 2]
index of max elemet in axis 0 of x=  [1 1 1]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [43]:
x = np.arange(10).reshape((5, 2))
print(x)
x.sum(axis=0)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([20, 25])

In [44]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[5, 6, 7], [8, 9, 10]])

v = np.array([9, 10, 11])
w = np.array([12, 13, 14])

# Inner product of vectors; both produce 392
print('v.w = ', v.dot(w))
print('v.w = ', np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [62 152]
print('x.v = ', x.dot(v))
print('x.v = ', np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print('x.y = ', x.dot(y.T))
print('x.y = ', np.dot(x, y.T))

v.w =  392
v.w =  392
x.v =  [ 62 152]
x.v =  [ 62 152]
x.y =  [[ 38  56]
 [ 92 137]]
x.y =  [[ 38  56]
 [ 92 137]]


NumPy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [45]:
x = np.array([[1, 2],[3, 4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


## Iteration

To iterate over NumPy arrays, do so as if iterating over a list

In [46]:
a = np.array([1, 4, 5, 10, 12, 15], int)

for number in a:
    print(number)

1
4
5
10
12
15


## Logical Operators
The output of these operations can be called mask.

In [48]:
# Create arrays with random integer values
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

print('a:', a)
print('b:', b)
print('a > b ', a > b)
print('a < b ', a < b)
print('a == b ', a == b)
print('a >= b ', a >= b)
print('a <= b ', a <= b)
print('a != b ', a != b)


a: [5 9 8 1 6]
b: [8 5 0 0 5]
a > b  [False  True  True  True  True]
a < b  [ True False False False False]
a == b  [False False False False False]
a >= b  [False  True  True  True  True]
a <= b  [ True False False False False]
a != b  [ True  True  True  True  True]


You can mix multiple rational operations together using bitwise operations

In [56]:
print('a: ', a)
print('a > 5 ', a > 5)
print('a < 9 ', a < 9)
print('(a > 5) & (a < 9)', (a > 5) & (a < 9)) # condition 1 and condition 2
print('(a > 5) | (a < 9)', (a > 5) | (a < 9)) # condition 1 or condition 2

a:  [5 9 8 1 6]
a > 5  [False  True  True False  True]
a < 9  [ True False  True  True  True]
(a > 5) & (a < 9) [False False  True False  True]
(a > 5) | (a < 9) [ True  True  True  True  True]
